FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# [추가] 빌드 시점에 주입받을 변수들 선언
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_NOTION_TERMS_URL
ARG NEXT_PUBLIC_NOTION_PRIVACY_URL
ARG NEXT_PUBLIC_NOTION_MARKETING_USE_URL
ARG NEXT_PUBLIC_NOTION_MARKETING_RECEIVE_URL

# [추가] 환경 변수로 등록 (Next.js 빌드 프로세스가 이 값을 사용함)
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_NOTION_TERMS_URL=$NEXT_PUBLIC_NOTION_TERMS_URL
ENV NEXT_PUBLIC_NOTION_PRIVACY_URL=$NEXT_PUBLIC_NOTION_PRIVACY_URL
ENV NEXT_PUBLIC_NOTION_MARKETING_USE_URL=$NEXT_PUBLIC_NOTION_MARKETING_USE_URL
ENV NEXT_PUBLIC_NOTION_MARKETING_RECEIVE_URL=$NEXT_PUBLIC_NOTION_MARKETING_RECEIVE_URL

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public



EXPOSE 3000
CMD ["npm", "start"]